
services:
  selenoid:
    container_name: selenoid
    network_mode: bridge
    image:  aerokube/selenoid:1.11.3
    ports:
      - "4444:4444"
    volumes:
      - "./browsers.json:/var/browsers.json"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - ".:/etc/selenoid"

  selenoid-ui:
    container_name: selenoid-ui
    network_mode: bridge
    image: aerokube/selenoid-ui:1.10.5
    ports:
      - "8081:8080"
    links:
      - selenoid
    depends_on:
      - selenoid
    command:
      - "--selenoid-uri=http://selenoid:4444"

  uiautotests:
    container_name: uiautotests
    network_mode: bridge
    build:
      context: .
      dockerfile: Dockerfile
    links:
      - selenoid
    depends_on:
      - selenoid
    environment:
      - JAVA_OPTS=-Dwebdriver.remote.url=http://selenoid:4444/wd/hub