services:
  selenoid:
    container_name: selenoid
    image: aerokube/selenoid:latest-release
    privileged: true
    shm_size: 2gb
    ports:
      - "4444:4444"
    volumes:
      - ./browsers.json:/browsers.json
      - /var/run/docker.sock:/var/run/docker.sock
    command:
      - "-limit"
      - "4"
      - "-conf"
      - "/browsers.json"
    healthcheck:
      test: [ "CMD", "wget", "--spider", "-q", "http://localhost:4444/status" ]
      interval: 10s
      timeout: 10s
      retries: 6
      start_period: 10s

  uiautotests:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      selenoid:
        condition: service_healthy
    environment:
      - JAVA_OPTS=-Dwebdriver.remote.url=http://selenoid:4444/wd/hub